project_id = "umjqoizuhfrxzjgrdvei"

[functions.analyze-receipt]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = true

[functions.save-transaction]
verify_jwt = true

[functions.save-opening-balance]
verify_jwt = true

[functions.save-invoice]
verify_jwt = true

[functions.save-payment]
verify_jwt = true

[functions.save-general-transaction]
verify_jwt = true

[functions.use-transaction-template]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true