-- FORTSÄTTNING: Resterande tillgångar (12xx-19xx)
INSERT INTO public.airledger_chart_of_accounts (account_code, account_name, account_type, account_category, normal_balance) VALUES

-- 12xx - Fortsättning maskiner och inventarier  
('1210', 'Maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'debit'),
('1211', 'Maskiner', 'asset', 'tangible_assets', 'debit'),
('1213', 'Andra tekniska anläggningar', 'asset', 'tangible_assets', 'debit'),
('1218', 'Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'credit'),
('1219', 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'credit'),
('1220', 'Inventarier och verktyg', 'asset', 'tangible_assets', 'debit'),
('1221', 'Inventarier', 'asset', 'tangible_assets', 'debit'),
('1222', 'Byggnadsinventarier', 'asset', 'tangible_assets', 'debit'),
('1223', 'Markinventarier', 'asset', 'tangible_assets', 'debit'),
('1225', 'Verktyg', 'asset', 'tangible_assets', 'debit'),
('1228', 'Ackumulerade nedskrivningar på inventarier och verktyg', 'asset', 'tangible_assets', 'credit'),
('1229', 'Ackumulerade avskrivningar på inventarier och verktyg', 'asset', 'tangible_assets', 'credit'),
('1230', 'Installationer', 'asset', 'tangible_assets', 'debit'),
('1231', 'Installationer på egen fastighet', 'asset', 'tangible_assets', 'debit'),
('1232', 'Installationer på annans fastighet', 'asset', 'tangible_assets', 'debit'),
('1238', 'Ackumulerade nedskrivningar på installationer', 'asset', 'tangible_assets', 'credit'),
('1239', 'Ackumulerade avskrivningar på installationer', 'asset', 'tangible_assets', 'credit'),
('1240', 'Bilar och andra transportmedel', 'asset', 'tangible_assets', 'debit'),
('1241', 'Personbilar', 'asset', 'tangible_assets', 'debit'),
('1242', 'Lastbilar', 'asset', 'tangible_assets', 'debit'),
('1243', 'Truckar', 'asset', 'tangible_assets', 'debit'),
('1244', 'Arbetsmaskiner', 'asset', 'tangible_assets', 'debit'),
('1245', 'Traktorer', 'asset', 'tangible_assets', 'debit'),
('1246', 'Motorcyklar, mopeder och skotrar', 'asset', 'tangible_assets', 'debit'),
('1247', 'Båtar, flygplan och helikoptrar', 'asset', 'tangible_assets', 'debit'),
('1248', 'Ackumulerade nedskrivningar på bilar och andra transportmedel', 'asset', 'tangible_assets', 'credit'),
('1249', 'Ackumulerade avskrivningar på bilar och andra transportmedel', 'asset', 'tangible_assets', 'credit'),
('1250', 'Datorer', 'asset', 'tangible_assets', 'debit'),
('1251', 'Datorer, företaget', 'asset', 'tangible_assets', 'debit'),
('1257', 'Datorer, personal', 'asset', 'tangible_assets', 'debit'),
('1258', 'Ackumulerade nedskrivningar på datorer', 'asset', 'tangible_assets', 'credit'),
('1259', 'Ackumulerade avskrivningar på datorer', 'asset', 'tangible_assets', 'credit'),
('1260', 'Leasade tillgångar', 'asset', 'tangible_assets', 'debit'),
('1269', 'Ackumulerade avskrivningar på leasade tillgångar', 'asset', 'tangible_assets', 'credit'),
('1280', 'Pågående nyanläggningar och förskott för maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1281', 'Pågående nyanläggningar, maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1288', 'Förskott för maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1290', 'Övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'debit'),
('1291', 'Konst och liknande tillgångar', 'asset', 'tangible_assets', 'debit'),
('1292', 'Djur som klassificeras som anläggningstillgång', 'asset', 'tangible_assets', 'debit'),
('1298', 'Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'credit'),
('1299', 'Ackumulerade avskrivningar på övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'credit'),

-- 13xx - Finansiella anläggningstillgångar
('1310', 'Andelar i koncernföretag', 'asset', 'financial_assets', 'debit'),
('1320', 'Fordringar hos koncernföretag', 'asset', 'financial_assets', 'debit'),
('1330', 'Andelar i intresseföretag', 'asset', 'financial_assets', 'debit'),
('1340', 'Fordringar hos intresseföretag', 'asset', 'financial_assets', 'debit'),
('1350', 'Andra långfristiga värdepappersinnehav', 'asset', 'financial_assets', 'debit'),
('1360', 'Andra långfristiga fordringar', 'asset', 'financial_assets', 'debit');