-- Continue inserting remaining BAS 2024 accounts - Batch 2: Skulder och resterande intäkter/kostnader

INSERT INTO public.airledger_chart_of_accounts (account_code, account_name, account_type, account_category, normal_balance) VALUES

-- SKULDER (fortsättning från 2100+)
-- Aktiekapital och fonder (aktiebolag)
('2081', 'Aktiekapital', 'equity', 'share_capital', 'credit'),
('2082', 'Reservfond', 'equity', 'reserves', 'credit'),
('2083', 'Uppskrivningsfond', 'equity', 'reserves', 'credit'),
('2084', 'Fond för utvecklingsutgifter', 'equity', 'reserves', 'credit'),
('2085', 'Överkursfond', 'equity', 'reserves', 'credit'),
('2086', 'Andra bundna fonder', 'equity', 'reserves', 'credit'),
('2087', 'Fria fonder', 'equity', 'reserves', 'credit'),
('2088', 'Balanserad vinst eller förlust', 'equity', 'retained_earnings', 'credit'),
('2089', 'Årets resultat', 'equity', 'retained_earnings', 'credit'),

-- Obeskattade reserver
('2091', 'Ackumulerade överavskrivningar', 'equity', 'tax_reserves', 'credit'),
('2092', 'Periodiseringsfonder', 'equity', 'tax_reserves', 'credit'),
('2093', 'Ersättningsfonder', 'equity', 'tax_reserves', 'credit'),
('2094', 'Expansionsfonder', 'equity', 'tax_reserves', 'credit'),
('2098', 'Andra obeskattade reserver', 'equity', 'tax_reserves', 'credit'),

-- Avsättningar
('2110', 'Avsättningar för pensioner och liknande förpliktelser', 'liability', 'provisions', 'credit'),
('2120', 'Avsättningar för skatter', 'liability', 'provisions', 'credit'),
('2130', 'Andra avsättningar', 'liability', 'provisions', 'credit'),
('2131', 'Avsättningar för garantiåtaganden', 'liability', 'provisions', 'credit'),
('2132', 'Avsättningar för omstrukturering', 'liability', 'provisions', 'credit'),
('2139', 'Övriga avsättningar', 'liability', 'provisions', 'credit'),

-- Långfristiga skulder
('2210', 'Banklån', 'liability', 'long_term_debt', 'credit'),
('2211', 'Banklån hos moderföretag', 'liability', 'long_term_debt', 'credit'),
('2212', 'Banklån hos dotterföretag', 'liability', 'long_term_debt', 'credit'),
('2213', 'Banklån hos andra koncernföretag', 'liability', 'long_term_debt', 'credit'),
('2214', 'Banklån hos intresseföretag', 'liability', 'long_term_debt', 'credit'),
('2220', 'Skulder till kreditinstitut', 'liability', 'long_term_debt', 'credit'),
('2230', 'Obligationslån', 'liability', 'long_term_debt', 'credit'),
('2240', 'Konvertibla skuldebrev', 'liability', 'long_term_debt', 'credit'),
('2250', 'Andra långfristiga skulder', 'liability', 'long_term_debt', 'credit'),
('2251', 'Skulder för finansiell leasing', 'liability', 'long_term_debt', 'credit'),
('2252', 'Anslutningsavgifter', 'liability', 'long_term_debt', 'credit'),
('2253', 'Skulder till delägare eller närstående', 'liability', 'long_term_debt', 'credit'),
('2258', 'Uppskjuten skatteskuld', 'liability', 'long_term_debt', 'credit'),
('2259', 'Övriga långfristiga skulder', 'liability', 'long_term_debt', 'credit'),

-- Kortfristiga skulder
('2410', 'Banklån', 'liability', 'short_term_debt', 'credit'),
('2411', 'Banklån hos moderföretag', 'liability', 'short_term_debt', 'credit'),
('2412', 'Banklån hos dotterföretag', 'liability', 'short_term_debt', 'credit'),
('2413', 'Banklån hos andra koncernföretag', 'liability', 'short_term_debt', 'credit'),
('2414', 'Banklån hos intresseföretag', 'liability', 'short_term_debt', 'credit'),
('2420', 'Skulder till kreditinstitut', 'liability', 'short_term_debt', 'credit'),
('2440', 'Förskott från kunder', 'liability', 'payables', 'credit'),
('2441', 'Förskott från kunder inom koncernen', 'liability', 'payables', 'credit'),
('2442', 'Förskott från kunder hos intresseföretag', 'liability', 'payables', 'credit'),
('2450', 'Leverantörsskulder', 'liability', 'payables', 'credit'),
('2451', 'Leverantörsskulder inom koncernen', 'liability', 'payables', 'credit'),
('2452', 'Leverantörsskulder hos intresseföretag', 'liability', 'payables', 'credit'),
('2460', 'Växelskulder', 'liability', 'payables', 'credit'),
('2470', 'Skatteskulder', 'liability', 'payables', 'credit'),
('2510', 'Kortfristiga skulder till anställda', 'liability', 'payables', 'credit'),
('2511', 'Löneskulder', 'liability', 'payables', 'credit'),
('2512', 'Semesterlöneskulder', 'liability', 'payables', 'credit'),
('2513', 'Skulder för lönebaserade skatter och avgifter', 'liability', 'payables', 'credit'),
('2514', 'Källskatteskulder', 'liability', 'payables', 'credit'),
('2515', 'Pensionsavsättningar (tryggandeavtal)', 'liability', 'payables', 'credit'),
('2516', 'Övriga skulder till anställda', 'liability', 'payables', 'credit'),
('2610', 'Utgående moms', 'liability', 'tax_liabilities', 'credit'),
('2611', 'Utgående moms på försäljning', 'liability', 'tax_liabilities', 'credit'),
('2630', 'Ingående moms', 'asset', 'tax_assets', 'debit'),
('2631', 'Ingående moms', 'asset', 'tax_assets', 'debit'),
('2640', 'Redovisningskonto för moms', 'liability', 'tax_liabilities', 'credit'),
('2710', 'Personalens källskatt', 'liability', 'payables', 'credit'),
('2730', 'Övriga kortfristiga skulder', 'liability', 'payables', 'credit'),
('2731', 'Kontraktsskulder', 'liability', 'payables', 'credit'),
('2732', 'Skulder för kontokort och kuponger', 'liability', 'payables', 'credit'),
('2740', 'Upplupna kostnader och förutbetalda intäkter', 'liability', 'accrued_liabilities', 'credit'),
('2741', 'Upplupna räntekostnader', 'liability', 'accrued_liabilities', 'credit'),
('2742', 'Upplupna hyresintäkter', 'liability', 'accrued_liabilities', 'credit'),
('2743', 'Upplupna lönekostnader', 'liability', 'accrued_liabilities', 'credit'),
('2744', 'Upplupna sociala kostnader', 'liability', 'accrued_liabilities', 'credit'),
('2745', 'Upplupna semesterlönekostnader', 'liability', 'accrued_liabilities', 'credit'),
('2790', 'Övriga upplupna kostnader och förutbetalda intäkter', 'liability', 'accrued_liabilities', 'credit'),

-- INTÄKTER (3000-3999)
('3000', 'Försäljning', 'income', 'sales', 'credit'),
('3001', 'Försäljning inom koncernen', 'income', 'sales', 'credit'),
('3002', 'Försäljning till intresseföretag', 'income', 'sales', 'credit'),
('3010', 'Försäljning av tjänster', 'income', 'services', 'credit'),
('3011', 'Försäljning av tjänster inom koncernen', 'income', 'services', 'credit'),
('3012', 'Försäljning av tjänster till intresseföretag', 'income', 'services', 'credit'),
('3020', 'Försäljning av abonnemang och medlemskap', 'income', 'services', 'credit'),
('3040', 'Hyresintäkter', 'income', 'rental', 'credit'),
('3041', 'Hyresintäkter inom koncernen', 'income', 'rental', 'credit'),
('3042', 'Hyresintäkter från intresseföretag', 'income', 'rental', 'credit'),
('3050', 'Provisionsintäkter', 'income', 'commission', 'credit'),
('3060', 'Licensintäkter och royalty', 'income', 'license', 'credit'),
('3070', 'Fakturerade frakter', 'income', 'freight', 'credit'),
('3100', 'Ränteintäkter från koncernföretag', 'income', 'interest', 'credit'),
('3101', 'Ränteintäkter från moderföretag', 'income', 'interest', 'credit'),
('3102', 'Ränteintäkter från dotterföretag', 'income', 'interest', 'credit'),
('3103', 'Ränteintäkter från andra koncernföretag', 'income', 'interest', 'credit'),
('3104', 'Ränteintäkter från intresseföretag', 'income', 'interest', 'credit'),
('3110', 'Övriga ränteintäkter', 'income', 'interest', 'credit'),
('3120', 'Utdelningsintäkter från koncernföretag', 'income', 'dividends', 'credit'),
('3130', 'Utdelningsintäkter från intresseföretag', 'income', 'dividends', 'credit'),
('3160', 'Övriga utdelningsintäkter', 'income', 'dividends', 'credit'),
('3200', 'Övriga rörelseintäkter', 'income', 'other_operating', 'credit'),
('3220', 'Vinst vid avyttring av materiella anläggningstillgångar', 'income', 'asset_disposal', 'credit'),
('3230', 'Vinst vid avyttring av finansiella anläggningstillgångar', 'income', 'financial_disposal', 'credit'),
('3240', 'Valutakursvinster', 'income', 'currency', 'credit'),
('3250', 'Återföring av nedskrivningar', 'income', 'reversals', 'credit'),
('3260', 'Erhållna bidrag och stöd', 'income', 'grants', 'credit'),
('3280', 'Övriga intäkter', 'income', 'other', 'credit'),
('3400', 'Aktiverat arbete för egen räkning', 'income', 'internal_work', 'credit'),
('3500', 'Lagerförändring, produkter i arbete', 'income', 'inventory_changes', 'credit'),
('3510', 'Lagerförändring, färdiga varor', 'income', 'inventory_changes', 'credit'),
('3520', 'Lagerförändring, pågående arbeten', 'income', 'inventory_changes', 'credit'),

-- KOSTNADER (4000-7999)
-- Råvaror och förnödenheter
('4000', 'Inköp av varor', 'expense', 'cost_of_goods', 'debit'),
('4001', 'Inköp av varor inom koncernen', 'expense', 'cost_of_goods', 'debit'),
('4002', 'Inköp av varor från intresseföretag', 'expense', 'cost_of_goods', 'debit'),
('4010', 'Inköp av råvaror', 'expense', 'cost_of_goods', 'debit'),
('4020', 'Inköp av material', 'expense', 'cost_of_goods', 'debit'),
('4030', 'Förändring av lager av handelsvaror', 'expense', 'cost_of_goods', 'debit'),
('4031', 'Förändring av lager av råvaror', 'expense', 'cost_of_goods', 'debit'),
('4040', 'Förändring av lager av material', 'expense', 'cost_of_goods', 'debit'),
('4050', 'Inköp av underentreprenader', 'expense', 'cost_of_goods', 'debit'),
('4060', 'Transportkostnader inköp', 'expense', 'cost_of_goods', 'debit'),
('4070', 'Tullar och avgifter', 'expense', 'cost_of_goods', 'debit'),
('4080', 'Lagersvinn', 'expense', 'cost_of_goods', 'debit'),
('4090', 'Övriga direkta kostnader', 'expense', 'cost_of_goods', 'debit'),

-- Övriga externa kostnader
('5000', 'Lokalhyra', 'expense', 'premises', 'debit'),
('5010', 'Leasingavgifter', 'expense', 'premises', 'debit'),
('5020', 'Elkostnad', 'expense', 'utilities', 'debit'),
('5030', 'Uppvärmning', 'expense', 'utilities', 'debit'),
('5040', 'Vatten och avlopp', 'expense', 'utilities', 'debit'),
('5050', 'Städning', 'expense', 'premises', 'debit'),
('5060', 'Reparationer av lokaler', 'expense', 'maintenance', 'debit'),
('5070', 'Fastighetsskatt', 'expense', 'premises', 'debit'),
('5080', 'Övriga lokalkostnader', 'expense', 'premises', 'debit'),
('5100', 'Kontorsmaterial', 'expense', 'office', 'debit'),
('5110', 'Trycksaker', 'expense', 'office', 'debit'),
('5120', 'Telekommunikation', 'expense', 'communication', 'debit'),
('5130', 'Programvaror', 'expense', 'office', 'debit'),
('5140', 'Förbrukningsmaterial', 'expense', 'office', 'debit'),
('5150', 'Tidningar och tidskrifter', 'expense', 'office', 'debit');