-- Replace BAS 2024 chart of accounts with complete data from CSV
-- First clear existing data
DELETE FROM public.airledger_chart_of_accounts;

-- Insert complete BAS 2024 chart of accounts
INSERT INTO public.airledger_chart_of_accounts (account_code, account_name, account_type, account_category, normal_balance) VALUES
-- TILLGÅNGAR (1000-1999)
-- Immateriella anläggningstillgångar
('1010', 'Utvecklingsutgifter', 'asset', 'intangible_assets', 'debit'),
('1011', 'Balanserade utgifter för forskning och utveckling', 'asset', 'intangible_assets', 'debit'),
('1012', 'Balanserade utgifter för programvaror', 'asset', 'intangible_assets', 'debit'),
('1018', 'Ackumulerade nedskrivningar på balanserade utgifter', 'asset', 'intangible_assets', 'credit'),
('1019', 'Ackumulerade avskrivningar på balanserade utgifter', 'asset', 'intangible_assets', 'credit'),
('1020', 'Koncessioner m.m.', 'asset', 'intangible_assets', 'debit'),
('1028', 'Ackumulerade nedskrivningar på koncessioner m.m.', 'asset', 'intangible_assets', 'credit'),
('1029', 'Ackumulerade avskrivningar på koncessioner m.m.', 'asset', 'intangible_assets', 'credit'),
('1030', 'Patent', 'asset', 'intangible_assets', 'debit'),
('1038', 'Ackumulerade nedskrivningar på patent', 'asset', 'intangible_assets', 'credit'),
('1039', 'Ackumulerade avskrivningar på patent', 'asset', 'intangible_assets', 'credit'),
('1040', 'Licenser', 'asset', 'intangible_assets', 'debit'),
('1048', 'Ackumulerade nedskrivningar på licenser', 'asset', 'intangible_assets', 'credit'),
('1049', 'Ackumulerade avskrivningar på licenser', 'asset', 'intangible_assets', 'credit'),
('1050', 'Varumärken', 'asset', 'intangible_assets', 'debit'),
('1058', 'Ackumulerade nedskrivningar på varumärken', 'asset', 'intangible_assets', 'credit'),
('1059', 'Ackumulerade avskrivningar på varumärken', 'asset', 'intangible_assets', 'credit'),
('1060', 'Hyresrätter, tomträtter och liknande', 'asset', 'intangible_assets', 'debit'),
('1068', 'Ackumulerade nedskrivningar på hyresrätter, tomträtter och liknande', 'asset', 'intangible_assets', 'credit'),
('1069', 'Ackumulerade avskrivningar på hyresrätter, tomträtter och liknande', 'asset', 'intangible_assets', 'credit'),
('1070', 'Goodwill', 'asset', 'intangible_assets', 'debit'),
('1078', 'Ackumulerade nedskrivningar på goodwill', 'asset', 'intangible_assets', 'credit'),
('1079', 'Ackumulerade avskrivningar på goodwill', 'asset', 'intangible_assets', 'credit'),
('1080', 'Förskott för immateriella anläggningstillgångar', 'asset', 'intangible_assets', 'debit'),
('1081', 'Pågående projekt för immateriella anläggningstillgångar', 'asset', 'intangible_assets', 'debit'),
('1088', 'Förskott för immateriella anläggningstillgångar', 'asset', 'intangible_assets', 'debit'),

-- Byggnader och mark
('1110', 'Byggnader', 'asset', 'tangible_assets', 'debit'),
('1111', 'Byggnader på egen mark', 'asset', 'tangible_assets', 'debit'),
('1112', 'Byggnader på annans mark', 'asset', 'tangible_assets', 'debit'),
('1118', 'Ackumulerade nedskrivningar på byggnader', 'asset', 'tangible_assets', 'credit'),
('1119', 'Ackumulerade avskrivningar på byggnader', 'asset', 'tangible_assets', 'credit'),
('1120', 'Förbättringsutgifter på annans fastighet', 'asset', 'tangible_assets', 'debit'),
('1129', 'Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet', 'asset', 'tangible_assets', 'credit'),
('1130', 'Mark', 'asset', 'tangible_assets', 'debit'),
('1140', 'Tomter och obebyggda markområden', 'asset', 'tangible_assets', 'debit'),
('1150', 'Markanläggningar', 'asset', 'tangible_assets', 'debit'),
('1158', 'Ackumulerade nedskrivningar på markanläggningar', 'asset', 'tangible_assets', 'credit'),
('1159', 'Ackumulerade avskrivningar på markanläggningar', 'asset', 'tangible_assets', 'credit'),
('1180', 'Pågående nyanläggningar och förskott för byggnader och mark', 'asset', 'tangible_assets', 'debit'),
('1181', 'Pågående ny-, till- och ombyggnad', 'asset', 'tangible_assets', 'debit'),
('1188', 'Förskott för byggnader och mark', 'asset', 'tangible_assets', 'debit'),

-- Maskiner och inventarier
('1210', 'Maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'debit'),
('1211', 'Maskiner', 'asset', 'tangible_assets', 'debit'),
('1213', 'Andra tekniska anläggningar', 'asset', 'tangible_assets', 'debit'),
('1218', 'Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'credit'),
('1219', 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar', 'asset', 'tangible_assets', 'credit'),
('1220', 'Inventarier och verktyg', 'asset', 'tangible_assets', 'debit'),
('1221', 'Inventarier', 'asset', 'tangible_assets', 'debit'),
('1222', 'Byggnadsinventarier', 'asset', 'tangible_assets', 'debit'),
('1223', 'Markinventarier', 'asset', 'tangible_assets', 'debit'),
('1225', 'Verktyg', 'asset', 'tangible_assets', 'debit'),
('1228', 'Ackumulerade nedskrivningar på inventarier och verktyg', 'asset', 'tangible_assets', 'credit'),
('1229', 'Ackumulerade avskrivningar på inventarier och verktyg', 'asset', 'tangible_assets', 'credit'),
('1230', 'Installationer', 'asset', 'tangible_assets', 'debit'),
('1231', 'Installationer på egen fastighet', 'asset', 'tangible_assets', 'debit'),
('1232', 'Installationer på annans fastighet', 'asset', 'tangible_assets', 'debit'),
('1238', 'Ackumulerade nedskrivningar på installationer', 'asset', 'tangible_assets', 'credit'),
('1239', 'Ackumulerade avskrivningar på installationer', 'asset', 'tangible_assets', 'credit'),
('1240', 'Bilar och andra transportmedel', 'asset', 'tangible_assets', 'debit'),
('1241', 'Personbilar', 'asset', 'tangible_assets', 'debit'),
('1242', 'Lastbilar', 'asset', 'tangible_assets', 'debit'),
('1243', 'Truckar', 'asset', 'tangible_assets', 'debit'),
('1244', 'Arbetsmaskiner', 'asset', 'tangible_assets', 'debit'),
('1245', 'Traktorer', 'asset', 'tangible_assets', 'debit'),
('1246', 'Motorcyklar, mopeder och skotrar', 'asset', 'tangible_assets', 'debit'),
('1247', 'Båtar, flygplan och helikoptrar', 'asset', 'tangible_assets', 'debit'),
('1248', 'Ackumulerade nedskrivningar på bilar och andra transportmedel', 'asset', 'tangible_assets', 'credit'),
('1249', 'Ackumulerade avskrivningar på bilar och andra transportmedel', 'asset', 'tangible_assets', 'credit'),
('1250', 'Datorer', 'asset', 'tangible_assets', 'debit'),
('1251', 'Datorer, företaget', 'asset', 'tangible_assets', 'debit'),
('1257', 'Datorer, personal', 'asset', 'tangible_assets', 'debit'),
('1258', 'Ackumulerade nedskrivningar på datorer', 'asset', 'tangible_assets', 'credit'),
('1259', 'Ackumulerade avskrivningar på datorer', 'asset', 'tangible_assets', 'credit'),
('1260', 'Leasade tillgångar', 'asset', 'tangible_assets', 'debit'),
('1269', 'Ackumulerade avskrivningar på leasade tillgångar', 'asset', 'tangible_assets', 'credit'),
('1280', 'Pågående nyanläggningar och förskott för maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1281', 'Pågående nyanläggningar, maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1288', 'Förskott för maskiner och inventarier', 'asset', 'tangible_assets', 'debit'),
('1290', 'Övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'debit'),
('1291', 'Konst och liknande tillgångar', 'asset', 'tangible_assets', 'debit'),
('1292', 'Djur som klassificeras som anläggningstillgång', 'asset', 'tangible_assets', 'debit'),
('1298', 'Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'credit'),
('1299', 'Ackumulerade avskrivningar på övriga materiella anläggningstillgångar', 'asset', 'tangible_assets', 'credit'),

-- Finansiella anläggningstillgångar
('1310', 'Andelar i koncernföretag', 'asset', 'financial_assets', 'debit'),
('1311', 'Aktier i noterade svenska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1312', 'Aktier i onoterade svenska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1313', 'Aktier i noterade utländska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1314', 'Aktier i onoterade utländska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1316', 'Andra andelar i svenska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1317', 'Andra andelar i utländska koncernföretag', 'asset', 'financial_assets', 'debit'),
('1318', 'Ackumulerade nedskrivningar av andelar i koncernföretag', 'asset', 'financial_assets', 'credit'),
('1320', 'Långfristiga fordringar hos koncernföretag', 'asset', 'financial_assets', 'debit'),
('1321', 'Långfristiga fordringar hos moderföretag', 'asset', 'financial_assets', 'debit'),
('1322', 'Långfristiga fordringar hos dotterföretag', 'asset', 'financial_assets', 'debit'),
('1323', 'Långfristiga fordringar hos andra koncernföretag', 'asset', 'financial_assets', 'debit'),
('1328', 'Ackumulerade nedskrivningar av långfristiga fordringar hos koncernföretag', 'asset', 'financial_assets', 'credit'),
('1330', 'Andelar i intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'debit'),
('1331', 'Andelar i intresseföretag', 'asset', 'financial_assets', 'debit'),
('1332', 'Ackumulerade nedskrivningar av andelar i intresseföretag', 'asset', 'financial_assets', 'credit'),
('1333', 'Andelar i gemensamt styrda företag', 'asset', 'financial_assets', 'debit'),
('1334', 'Ackumulerade nedskrivningar av andelar i gemensamt styrda företag', 'asset', 'financial_assets', 'credit'),
('1336', 'Andelar i övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'debit'),
('1337', 'Ackumulerade nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'credit'),
('1338', 'Ackumulerade nedskrivningar av andelar i intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'credit'),
('1340', 'Långfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'debit'),
('1341', 'Långfristiga fordringar hos intresseföretag', 'asset', 'financial_assets', 'debit'),
('1342', 'Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag', 'asset', 'financial_assets', 'credit'),
('1343', 'Långfristiga fordringar hos gemensamt styrda företag', 'asset', 'financial_assets', 'debit'),
('1344', 'Ackumulerade nedskrivningar av långfristiga fordringar hos gemensamt styrda företag', 'asset', 'financial_assets', 'credit'),
('1346', 'Långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'debit'),
('1347', 'Ackumulerade nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'credit'),
('1348', 'Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'financial_assets', 'credit'),
('1350', 'Andelar och värdepapper i andra företag', 'asset', 'financial_assets', 'debit'),
('1351', 'Andelar i noterade företag', 'asset', 'financial_assets', 'debit'),
('1352', 'Andra andelar', 'asset', 'financial_assets', 'debit'),
('1353', 'Andelar i bostadsrättsföreningar', 'asset', 'financial_assets', 'debit'),
('1354', 'Obligationer', 'asset', 'financial_assets', 'debit'),
('1356', 'Andelar i ekonomiska föreningar, övriga företag', 'asset', 'financial_assets', 'debit'),
('1357', 'Andelar i handelsbolag, andra företag', 'asset', 'financial_assets', 'debit'),
('1358', 'Ackumulerade nedskrivningar av andra andelar och värdepapper', 'asset', 'financial_assets', 'credit'),
('1360', 'Lån till delägare eller närstående enligt ABL, långfristig del', 'asset', 'financial_assets', 'debit'),
('1369', 'Ackumulerade nedskrivningar av lån till delägare eller närstående enligt ABL, långfristig del', 'asset', 'financial_assets', 'credit'),
('1370', 'Uppskjuten skattefordran', 'asset', 'financial_assets', 'debit'),
('1380', 'Andra långfristiga fordringar', 'asset', 'financial_assets', 'debit'),
('1381', 'Långfristiga reversfordringar', 'asset', 'financial_assets', 'debit'),
('1382', 'Långfristiga fordringar hos anställda', 'asset', 'financial_assets', 'debit'),
('1383', 'Lämnade depositioner, långfristiga', 'asset', 'financial_assets', 'debit'),
('1384', 'Derivat', 'asset', 'financial_assets', 'debit'),
('1385', 'Kapitalförsäkring', 'asset', 'financial_assets', 'debit'),
('1387', 'Långfristiga kontraktsfordringar', 'asset', 'financial_assets', 'debit'),
('1388', 'Långfristiga kundfordringar', 'asset', 'financial_assets', 'debit'),
('1389', 'Ackumulerade nedskrivningar av andra långfristiga fordringar', 'asset', 'financial_assets', 'credit'),

-- Lager, produkter i arbete och pågående arbeten
('1410', 'Lager av råvaror', 'asset', 'inventory', 'debit'),
('1419', 'Förändring av lager av råvaror', 'asset', 'inventory', 'debit'),
('1420', 'Lager av tillsatsmaterial och förnödenheter', 'asset', 'inventory', 'debit'),
('1429', 'Förändring av lager av tillsatsmaterial och förnödenheter', 'asset', 'inventory', 'debit'),
('1440', 'Produkter i arbete', 'asset', 'inventory', 'debit'),
('1449', 'Förändring av produkter i arbete', 'asset', 'inventory', 'debit'),
('1450', 'Lager av färdiga varor', 'asset', 'inventory', 'debit'),
('1459', 'Förändring av lager av färdiga varor', 'asset', 'inventory', 'debit'),
('1460', 'Lager av handelsvaror', 'asset', 'inventory', 'debit'),
('1465', 'Lager av varor VMB', 'asset', 'inventory', 'debit'),
('1466', 'Nedskrivning av varor VMB', 'asset', 'inventory', 'credit'),
('1467', 'Lager av varor VMB förenklad', 'asset', 'inventory', 'debit'),
('1469', 'Förändring av lager av handelsvaror', 'asset', 'inventory', 'debit'),
('1470', 'Pågående arbeten', 'asset', 'inventory', 'debit'),
('1471', 'Pågående arbeten, nedlagda kostnader', 'asset', 'inventory', 'debit'),
('1478', 'Pågående arbeten, fakturering', 'asset', 'inventory', 'credit'),
('1479', 'Förändring av pågående arbeten', 'asset', 'inventory', 'debit'),
('1480', 'Förskott för varor och tjänster', 'asset', 'inventory', 'debit'),
('1481', 'Remburser', 'asset', 'inventory', 'debit'),
('1489', 'Övriga förskott till leverantörer', 'asset', 'inventory', 'debit'),
('1490', 'Övriga lagertillgångar', 'asset', 'inventory', 'debit'),
('1491', 'Lager av värdepapper', 'asset', 'inventory', 'debit'),
('1492', 'Lager av fastigheter', 'asset', 'inventory', 'debit'),
('1493', 'Djur som klassificeras som omsättningstillgång', 'asset', 'inventory', 'debit'),

-- Kundfordringar
('1510', 'Kundfordringar', 'asset', 'receivables', 'debit'),
('1511', 'Kundfordringar', 'asset', 'receivables', 'debit'),
('1512', 'Belånade kundfordringar (factoring)', 'asset', 'receivables', 'debit'),
('1513', 'Kundfordringar – delad faktura', 'asset', 'receivables', 'debit'),
('1516', 'Tvistiga kundfordringar', 'asset', 'receivables', 'debit'),
('1518', 'Ej reskontraförda kundfordringar', 'asset', 'receivables', 'debit'),
('1519', 'Nedskrivning av kundfordringar', 'asset', 'receivables', 'credit'),
('1520', 'Växelfordringar', 'asset', 'receivables', 'debit'),
('1525', 'Osäkra växelfordringar', 'asset', 'receivables', 'debit'),
('1529', 'Nedskrivning av växelfordringar', 'asset', 'receivables', 'credit'),
('1530', 'Kontraktsfordringar', 'asset', 'receivables', 'debit'),
('1531', 'Kontraktsfordringar', 'asset', 'receivables', 'debit'),
('1532', 'Belånade kontraktsfordringar', 'asset', 'receivables', 'debit'),
('1536', 'Tvistiga kontraktsfordringar', 'asset', 'receivables', 'debit'),
('1539', 'Nedskrivning av kontraktsfordringar', 'asset', 'receivables', 'credit'),
('1550', 'Konsignationsfordringar', 'asset', 'receivables', 'debit'),
('1560', 'Kundfordringar hos koncernföretag', 'asset', 'receivables', 'debit'),
('1561', 'Kundfordringar hos moderföretag', 'asset', 'receivables', 'debit'),
('1562', 'Kundfordringar hos dotterföretag', 'asset', 'receivables', 'debit'),
('1563', 'Kundfordringar hos andra koncernföretag', 'asset', 'receivables', 'debit'),
('1568', 'Ej reskontraförda kundfordringar hos koncernföretag', 'asset', 'receivables', 'debit'),
('1569', 'Nedskrivning av kundfordringar hos koncernföretag', 'asset', 'receivables', 'credit'),
('1570', 'Kundfordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'receivables', 'debit'),
('1571', 'Kundfordringar hos intresseföretag', 'asset', 'receivables', 'debit'),
('1572', 'Kundfordringar hos gemensamt styrda företag', 'asset', 'receivables', 'debit'),
('1573', 'Kundfordringar hos övriga företag som det finns ett ägarintresse i', 'asset', 'receivables', 'debit'),
('1580', 'Fordringar för kontokort och kuponger', 'asset', 'receivables', 'debit'),

-- Övriga kortfristiga fordringar
('1610', 'Kortfristiga fordringar hos anställda', 'asset', 'receivables', 'debit'),
('1611', 'Reseförskott', 'asset', 'receivables', 'debit'),
('1612', 'Kassaförskott', 'asset', 'receivables', 'debit'),
('1613', 'Övriga förskott', 'asset', 'receivables', 'debit'),
('1614', 'Tillfälliga lån till anställda', 'asset', 'receivables', 'debit'),
('1619', 'Övriga fordringar hos anställda', 'asset', 'receivables', 'debit'),
('1620', 'Upparbetad men ej fakturerad intäkt', 'asset', 'receivables', 'debit'),
('1630', 'Avräkning för skatter och avgifter (skattekonto)', 'asset', 'receivables', 'debit'),
('1640', 'Skattefordringar', 'asset', 'receivables', 'debit'),
('1650', 'Momsfordran', 'asset', 'receivables', 'debit'),
('1660', 'Kortfristiga fordringar hos koncernföretag', 'asset', 'receivables', 'debit'),
('1661', 'Kortfristiga fordringar hos moderföretag', 'asset', 'receivables', 'debit'),
('1662', 'Kortfristiga fordringar hos dotterföretag', 'asset', 'receivables', 'debit'),
('1663', 'Kortfristiga fordringar hos andra koncernföretag', 'asset', 'receivables', 'debit'),
('1670', 'Kortfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i', 'asset', 'receivables', 'debit'),
('1671', 'Kortfristiga fordringar hos intresseföretag', 'asset', 'receivables', 'debit'),
('1672', 'Kortfristiga fordringar hos gemensamt styrda företag', 'asset', 'receivables', 'debit'),
('1673', 'Kortfristiga fordringar hos övriga företag som det finns ett ägarintresse i', 'asset', 'receivables', 'debit'),
('1680', 'Andra kortfristiga fordringar', 'asset', 'receivables', 'debit'),
('1681', 'Utlägg för kunder', 'asset', 'receivables', 'debit'),
('1682', 'Kortfristiga lånefordringar', 'asset', 'receivables', 'debit'),
('1683', 'Derivat', 'asset', 'receivables', 'debit'),
('1684', 'Kortfristiga fordringar hos leverantörer', 'asset', 'receivables', 'debit'),
('1685', 'Kortfristiga fordringar hos delägare eller närstående', 'asset', 'receivables', 'debit'),
('1687', 'Kortfristig del av långfristiga fordringar', 'asset', 'receivables', 'debit'),
('1688', 'Fordran arbetsmarknadsförsäkringar', 'asset', 'receivables', 'debit'),
('1689', 'Övriga kortfristiga fordringar', 'asset', 'receivables', 'debit'),
('1690', 'Fordringar för tecknat men ej inbetalt aktiekapital', 'asset', 'receivables', 'debit'),

-- Förutbetalda kostnader och upplupna intäkter
('1710', 'Förutbetalda hyreskostnader', 'asset', 'prepaid_accrued', 'debit'),
('1720', 'Förutbetalda leasingavgifter', 'asset', 'prepaid_accrued', 'debit'),
('1730', 'Förutbetalda försäkringspremier', 'asset', 'prepaid_accrued', 'debit'),
('1740', 'Förutbetalda räntekostnader', 'asset', 'prepaid_accrued', 'debit'),
('1750', 'Upplupna hyresintäkter', 'asset', 'prepaid_accrued', 'debit'),
('1760', 'Upplupna ränteintäkter', 'asset', 'prepaid_accrued', 'debit'),
('1770', 'Tillgångar av kostnadsnatur', 'asset', 'prepaid_accrued', 'debit'),
('1780', 'Upplupna avtalsintäkter', 'asset', 'prepaid_accrued', 'debit'),
('1790', 'Övriga förutbetalda kostnader och upplupna intäkter', 'asset', 'prepaid_accrued', 'debit'),

-- Kortfristiga placeringar
('1810', 'Andelar i börsnoterade företag', 'asset', 'short_term_investments', 'debit'),
('1820', 'Obligationer', 'asset', 'short_term_investments', 'debit'),
('1830', 'Konvertibla skuldebrev', 'asset', 'short_term_investments', 'debit'),
('1860', 'Andelar i koncernföretag, kortfristigt', 'asset', 'short_term_investments', 'debit'),
('1880', 'Andra kortfristiga placeringar', 'asset', 'short_term_investments', 'debit'),
('1886', 'Derivat', 'asset', 'short_term_investments', 'debit'),
('1889', 'Andelar i övriga företag', 'asset', 'short_term_investments', 'debit'),
('1890', 'Nedskrivning av kortfristiga placeringar', 'asset', 'short_term_investments', 'credit'),

-- Kassa och bank
('1910', 'Kassa', 'asset', 'cash', 'debit'),
('1911', 'Huvudkassa', 'asset', 'cash', 'debit'),
('1912', 'Kassa 2', 'asset', 'cash', 'debit'),
('1913', 'Kassa 3', 'asset', 'cash', 'debit'),
('1920', 'PlusGiro', 'asset', 'cash', 'debit'),
('1930', 'Företagskonto/checkkonto/affärskonto', 'asset', 'cash', 'debit'),
('1940', 'Övriga bankkonton', 'asset', 'cash', 'debit'),
('1950', 'Bankcertifikat', 'asset', 'cash', 'debit'),
('1960', 'Koncernkonto moderföretag', 'asset', 'cash', 'debit'),
('1970', 'Särskilda bankkonton', 'asset', 'cash', 'debit'),
('1972', 'Upphovsmannakonto', 'asset', 'cash', 'debit'),
('1973', 'Skogskonto', 'asset', 'cash', 'debit'),
('1974', 'Spärrade bankmedel', 'asset', 'cash', 'debit'),
('1979', 'Övriga särskilda bankkonton', 'asset', 'cash', 'debit'),
('1980', 'Valutakonton', 'asset', 'cash', 'debit'),
('1990', 'Redovisningsmedel', 'asset', 'cash', 'debit'),

-- EGET KAPITAL OCH SKULDER (2000-2999)
-- Eget kapital (enskild firma)
('2010', 'Eget kapital', 'equity', 'owner_equity', 'credit'),
('2011', 'Egna varuuttag', 'equity', 'owner_equity', 'debit'),
('2013', 'Övriga egna uttag', 'equity', 'owner_equity', 'debit'),
('2017', 'Årets kapitaltillskott', 'equity', 'owner_equity', 'credit'),
('2018', 'Övriga egna insättningar', 'equity', 'owner_equity', 'credit'),
('2019', 'Årets resultat', 'equity', 'owner_equity', 'credit'),

-- Eget kapital (delägare)
('2020', 'Eget kapital, delägare 2', 'equity', 'owner_equity', 'credit'),
('2021', 'Egna varuuttag, delägare 2', 'equity', 'owner_equity', 'debit'),
('2023', 'Övriga egna uttag, delägare 2', 'equity', 'owner_equity', 'debit'),
('2027', 'Årets kapitaltillskott, delägare 2', 'equity', 'owner_equity', 'credit'),
('2028', 'Övriga egna insättningar, delägare 2', 'equity', 'owner_equity', 'credit'),
('2029', 'Årets resultat, delägare 2', 'equity', 'owner_equity', 'credit'),

('2030', 'Eget kapital, delägare 3', 'equity', 'owner_equity', 'credit'),
('2031', 'Egna varuuttag, delägare 3', 'equity', 'owner_equity', 'debit'),
('2033', 'Övriga egna uttag, delägare 3', 'equity', 'owner_equity', 'debit'),
('2037', 'Årets kapitaltillskott, delägare 3', 'equity', 'owner_equity', 'credit'),
('2038', 'Övriga egna insättningar, delägare 3', 'equity', 'owner_equity', 'credit'),
('2039', 'Årets resultat, delägare 3', 'equity', 'owner_equity', 'credit'),

('2040', 'Eget kapital, delägare 4', 'equity', 'owner_equity', 'credit'),
('2041', 'Egna varuuttag, delägare 4', 'equity', 'owner_equity', 'debit'),
('2043', 'Övriga egna uttag, delägare 4', 'equity', 'owner_equity', 'debit'),
('2047', 'Årets kapitaltillskott, delägare 4', 'equity', 'owner_equity', 'credit'),
('2048', 'Övriga egna insättningar, delägare 4', 'equity', 'owner_equity', 'credit'),
('2049', 'Årets resultat, delägare 4', 'equity', 'owner_equity', 'credit'),

('2050', 'Avsättning till expansionsfond', 'equity', 'reserves', 'credit'),
('2060', 'Eget kapital i ideella föreningar, stiftelser och registrerade trossamfund', 'equity', 'owner_equity', 'credit'),
('2061', 'Eget kapital/stiftelsekapital/grundkapital', 'equity', 'owner_equity', 'credit'),
('2065', 'Förändring i fond för verkligt värde', 'equity', 'reserves', 'credit'),
('2066', 'Värdesäkringsfond', 'equity', 'reserves', 'credit'),
('2067', 'Balanserad vinst eller förlust/balanserat kapital', 'equity', 'retained_earnings', 'credit');