-- Insert new system templates for common transaction types
INSERT INTO airledger_transaction_templates (user_id, is_system_template, template_name, description, category, keywords, template_entries) VALUES

('00000000-0000-0000-0000-000000000000', true, 'Löneutbetalning', 'Utbetalning av nettolön till anställd efter skatteavdrag', 'Lön och personal', ARRAY['lön','nettolön','utbetalning','anställd','salary'], '[{"type":"debit","account_code":"7010","account_name":"Löner till kollektivanställda","description":"Bruttolön"},{"type":"credit","account_code":"2710","account_name":"Personalens källskatt","description":"Skatteavdrag"},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Utbetalning nettolön"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Ränteintäkt', 'Ränteintäkt från bank eller placering (momsfritt)', 'Finansiellt', ARRAY['ränta','ränteintäkt','bankränta','avkastning'], '[{"type":"debit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Ränta insatt","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"8310","account_name":"Ränteintäkter","description":"Ränteintäkt","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Räntekostnad', 'Räntekostnad på lån eller kredit (momsfritt)', 'Finansiellt', ARRAY['ränta','räntekostnad','lån','kredit'], '[{"type":"debit","account_code":"8410","account_name":"Räntekostnader","description":"Räntekostnad","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning ränta","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Köp inventarier (med moms)', 'Inköp av inventarier/utrustning från företag med 25% moms', 'Inventarier', ARRAY['inventarier','utrustning','möbler','dator','maskin','köp','inköp'], '[{"type":"debit","account_code":"1220","account_name":"Inventarier och verktyg","description":"Inventarie exkl moms","is_vat_base":true,"debit_amount":"{amount_excluding_vat}","credit_amount":0},{"type":"debit","account_code":"2640","account_name":"Ingående moms","description":"Moms 25%","is_vat_account":true,"vat_rate":0.25,"debit_amount":"{vat_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Köp inventarier (momsfritt)', 'Inköp av begagnade inventarier från privatperson utan moms', 'Inventarier', ARRAY['begagnat','blocket','privat','inventarier','momsfritt','begagnad'], '[{"type":"debit","account_code":"1220","account_name":"Inventarier och verktyg","description":"Inventarie begagnad","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning kontant","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Leverantörsbetalning', 'Betalning av leverantörsfaktura som redan bokförts', 'Betalningar', ARRAY['leverantör','faktura','betala','leverantörsfaktura','betalning'], '[{"type":"debit","account_code":"2440","account_name":"Leverantörsskulder","description":"Minskning leverantörsskuld","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Eget uttag', 'Ägare tar ut pengar från företaget (enskild firma)', 'Eget kapital', ARRAY['uttag','eget uttag','privat','ta ut','ägare'], '[{"type":"debit","account_code":"2013","account_name":"Övriga egna uttag","description":"Eget uttag","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Utbetalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Eget insättning', 'Ägare sätter in pengar i företaget (enskild firma)', 'Eget kapital', ARRAY['insättning','eget insättning','tillskott','ägare','sätta in'], '[{"type":"debit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Insättning","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"2018","account_name":"Övriga egna insättningar","description":"Eget insättning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Resekostnad', 'Tjänsteresor, tåg, flyg, taxi (med 25% moms)', 'Resekostnader', ARRAY['resa','tåg','flyg','taxi','reseräkning','tjänsteresa'], '[{"type":"debit","account_code":"5800","account_name":"Resekostnader","description":"Resekostnad exkl moms","is_vat_base":true,"debit_amount":"{amount_excluding_vat}","credit_amount":0},{"type":"debit","account_code":"2640","account_name":"Ingående moms","description":"Moms 25%","is_vat_account":true,"vat_rate":0.25,"debit_amount":"{vat_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Utbildning/Kurser', 'Utbildning och kurser för personal (med 25% moms)', 'Lön och personal', ARRAY['utbildning','kurs','seminarium','konferens','fortbildning'], '[{"type":"debit","account_code":"7620","account_name":"Utbildning","description":"Utbildningskostnad exkl moms","is_vat_base":true,"debit_amount":"{amount_excluding_vat}","credit_amount":0},{"type":"debit","account_code":"2640","account_name":"Ingående moms","description":"Moms 25%","is_vat_account":true,"vat_rate":0.25,"debit_amount":"{vat_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Revision/Bokföringstjänst', 'Kostnad för revisor eller redovisningstjänst (med 25% moms)', 'Kontorskostnader', ARRAY['revisor','bokföring','redovisning','revision','konsult'], '[{"type":"debit","account_code":"6530","account_name":"Redovisningstjänster","description":"Revisionskostnad exkl moms","is_vat_base":true,"debit_amount":"{amount_excluding_vat}","credit_amount":0},{"type":"debit","account_code":"2640","account_name":"Ingående moms","description":"Moms 25%","is_vat_account":true,"vat_rate":0.25,"debit_amount":"{vat_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Avskrivning inventarier', 'Månatlig/årlig avskrivning av inventarier och verktyg', 'Avskrivningar', ARRAY['avskrivning','avskriva','inventarier','värdeminskning'], '[{"type":"debit","account_code":"7832","account_name":"Avskrivningar inventarier och verktyg","description":"Avskrivning","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1229","account_name":"Ack avskrivningar inventarier och verktyg","description":"Ack avskrivning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb),

('00000000-0000-0000-0000-000000000000', true, 'Porto/Frakt', 'Porto och fraktkostnader', 'Kontorskostnader', ARRAY['porto','frakt','paket','brev','post','leverans'], '[{"type":"debit","account_code":"6250","account_name":"Postbefordran","description":"Porto/frakt","debit_amount":"{total_amount}","credit_amount":0},{"type":"credit","account_code":"1930","account_name":"Företagskonto/affärskonto","description":"Betalning","debit_amount":0,"credit_amount":"{total_amount}"}]'::jsonb);